version = 0.1

[default.deploy.parameters]
stack_name = "satisfactory-server"
resolve_s3 = true
s3_prefix = "satisfactory-server"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"dev\" VpcCIDR=\"10.192.0.0/16\" PublicSubnet1CIDR=\"10.192.10.0/24\" PrivateSubnet1CIDR=\"10.192.20.0/24\""
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
