AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LAMP / Prestashop stack

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: dev

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

  AdminCidr:
    Description: IP address in CIDR format for admin access
    Type: String

  IndexDocument:
    Type: String
    Description: "The index document"
    Default: "index.php"

  ErrorDocument:
    Type: String
    Description: "The error document, ignored in SPA mode"
    Default: "404.html"

  CloudFrontPriceClass:
    Type: String
    Description: "The price class for CloudFront distribution"
    Default: "PriceClass_100"
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All

#  LatestAmazonLinuxAMI:
#    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
#    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
#
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet (AZ1)

  EC2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: Prestashop EC2 instance

  EC2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EC2EIP.AllocationId
      InstanceId: !Ref EC2Instance

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Routes (AZ1)

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "server-sg"
      GroupDescription: "Security group with server ingress"
      VpcId: !Ref VPC

  ServerAdminIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: !Ref AdminCidr
      Description: SSH access
      FromPort: 22
      GroupId: !GetAtt ServerSecurityGroup.GroupId
      IpProtocol: tcp
      ToPort: 22

  ServerAccessHttpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: http access
      FromPort: 80
      GroupId: !GetAtt ServerSecurityGroup.GroupId
      IpProtocol: tcp
      ToPort: 80

#  ServerAccessHttpsIngress:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      CidrIp: "0.0.0.0/0"
#      Description: https access
#      FromPort: 443
#      GroupId: !GetAtt ServerSecurityGroup.GroupId
#      IpProtocol: tcp
#      ToPort: 443

  #  ServerBucketReadRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#                - ec2.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Path: /
#      Policies:
#        - PolicyName: S3-read-only-access
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              - Effect: Allow
#                Action:
#                  - s3:GetObject
#                  - s3:ListBucket
#                Resource:
#                  - !Sub "arn:aws:s3:::${Artefacts}"
#                  - !Sub "arn:aws:s3:::${Artefacts}/*"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00a89065114e84516
      KeyName: !Ref KeyPair
#      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: t4g.nano
      SecurityGroupIds:
        - !Ref ServerSecurityGroup
      SubnetId: !Ref PublicSubnet1
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 8
            DeleteOnTermination: false
            Encrypted: true

#  InstanceProfile:
#    Type: 'AWS::IAM::InstanceProfile'
#    Properties:
#      Path: /
#      Roles:
#        - !Ref ServerBucketReadRole

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: PrestashopKeyPair
      PublicKeyMaterial: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcv6/40kT3czgeeCSzr5bZqRAmBr8xJxbG/qTZxYsiu31aO4Zn84wbsCIm+3UAra1dXXMbEq5Zgp9R9lf7RkblB+ty4HesSqlDioPTs4bNTWbPFFC9JHUQNZiO6Sg6NMGHgJnswQVExoCcqrtnr6LUUcV9O7Cjruj3azR++huB7UcU+QuSKAVDP3rBy7UCYizsb+kotHXe0woMtT9qyBXigMrzl+hMMeI6Po27JMVXCLPp2ilizpxrv6cQCbG2sl/A4ocrZkVLk2o8s1Y+AXDt+IA+5pzWpA7NJ8etQEtvZ4I/QWpEYv61mVvDIHGfvl2rC2QBwRJlsvmx8tm7hJ2qgo3NQKRyPppUeq8Ppoexj/IdCNakY7LwCANq+tRu21Z8TfkMiAX2Gm8/BHW7uLe39BYfn2OAUZIknFnKI0oT0De3Tq4gYlT/wP7v8Qlf2YlJwOFjKmH+EAGLtckUjon8eu8mWkdYEwjyY7pNsVKikbPxeMzdaR8YeV9JHoV40oE= ddunford@UK-RXY2Y22G2X

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-loggingbucket"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetBucketAcl"
              - "s3:PutBucketAcl"
            Resource: !Sub "arn:aws:s3:::${LoggingBucket}"
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'

#  OriginAccessIdentity:
#    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
#    Properties:
#      CloudFrontOriginAccessIdentityConfig:
#        Comment: !Ref AWS::StackName
#
  RewriteRequestStaticFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-req-static"
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          var request = event.request;
          var uri = request.uri
          if (uri.endsWith('/')) {
              request.uri += '${IndexDocument}';
          } else if (!uri.includes('.')) {
              request.uri += '/${IndexDocument}';
          }
          return request;
        }
      FunctionConfig:
        Comment: !Sub "rewrite all paths to /${IndexDocument}"
        Runtime: cloudfront-js-1.0

  NoCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: No caching
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: 0
        Name: NoCache
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: EC2Instance
    Properties:
      DistributionConfig:
        Enabled: 'true'
        Comment: !Ref AWS::StackName
        DefaultRootObject: !Ref IndexDocument
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCachingMinTTL: 86400
            ErrorCode: 403 # object not found in bucket
            ResponseCode: 404
            ResponsePagePath: !Sub "/${ErrorDocument}"
        Origins:
          - DomainName: !GetAtt EC2Instance.PublicDnsName
            Id: root
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
            OriginCustomHeaders:
              - HeaderName: X-Forwarded-Proto
                HeaderValue: https
              - HeaderName: X-Scheme
                HeaderValue: https
              - HeaderName: SSL
                HeaderValue: "on"
        DefaultCacheBehavior:
          Compress: false
          CachedMethods:
            - GET
            - HEAD
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          TargetOriginId: root
          CachePolicyId: !Ref NoCachePolicy
          ViewerProtocolPolicy: https-only
          OriginRequestPolicyId: !Ref DistributionPolicy
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt RewriteRequestStaticFunction.FunctionMetadata.FunctionARN
        PriceClass: !Ref CloudFrontPriceClass
        Logging:
          Bucket: !Sub "${LoggingBucket}.s3.amazonaws.com"
          IncludeCookies: false
          Prefix: ""
        Aliases:
          - breezingclothing.co.uk
          - www.breezingclothing.co.uk
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:430828578942:certificate/7f6a8e31-3f17-49dd-a6e8-5385c631916e
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  DistributionPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: allViewer
        Name: passthrough
        QueryStringsConfig:
          QueryStringBehavior: all

  DistributionMonitoringSubscription:
    Type: AWS::CloudFront::MonitoringSubscription
    Properties:
      DistributionId: !Ref Distribution
      MonitoringSubscription:
        RealtimeMetricsSubscriptionConfig:
          RealtimeMetricsSubscriptionStatus: "Enabled"

  AccessLogsGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: !Sub "access-logs-${AWS::StackName}"
        Name: !Sub "access-logs-${AWS::StackName}"

  AccessLogsGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AccessLogsGlueDatabase
      TableInput:
        Name: 'access-logs'
        Description: 'Gzip logs delivered by Amazon CloudFront partitioned'
        TableType: EXTERNAL_TABLE
        Parameters: { "skip.header.line.count": "2" }
        StorageDescriptor:
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: IgnoreKeyTextOutputFormat
          Columns:
            - Name: date
              Type: date
            - Name: time
              Type: string
            - Name: location
              Type: string
            - Name: bytes
              Type: bigint
            - Name: request_ip
              Type: string
            - Name: method
              Type: string
            - Name: host
              Type: string
            - Name: uri
              Type: string
            - Name: status
              Type: int
            - Name: referrer
              Type: string
            - Name: user_agent
              Type: string
            - Name: query_string
              Type: string
            - Name: cookie
              Type: string
            - Name: result_type
              Type: string
            - Name: request_id
              Type: string
            - Name: host_header
              Type: string
            - Name: request_protocol
              Type: string
            - Name: request_bytes
              Type: bigint
            - Name: time_taken
              Type: float
            - Name: xforwarded_for
              Type: string
            - Name: ssl_protocol
              Type: string
            - Name: ssl_cipher
              Type: string
            - Name: response_result_type
              Type: string
            - Name: http_version
              Type: string
            - Name: fle_status
              Type: string
            - Name: fle_encrypted_fields
              Type: int
            - Name: c_port
              Type: int
            - Name: time_to_first_byte
              Type: float
            - Name: x_edge_detailed_result_type
              Type: string
            - Name: sc_content_type
              Type: string
            - Name: sc_content_len
              Type: bigint
            - Name: sc_range_start
              Type: bigint
            - Name: sc_range_end
              Type: bigint
          Location: !Sub "s3://${AWS::StackName}-${AWS::AccountId}-loggingbucket/"
          SerdeInfo:
            Parameters:
              field.delim: "\t"
              serialization.format: "\t"
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe

  AccessLogsAthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Description: !Sub "access-logs-${AWS::StackName}"
      Name: !Sub "access-logs-${AWS::StackName}"
      RecursiveDeleteOption: true
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: "SSE_S3"
          ExpectedBucketOwner: !Ref AWS::AccountId
          OutputLocation: !Sub "s3://${AccessLogsAthenaResultBucket}/"

  AccessLogsAthenaResultBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-accesslogs"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpiryRule
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 1
            Status: Enabled


Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1 ]]

  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1 ]]

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
