AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LAMP / Prestashop stack
Globals:
  Function:
    Timeout: 3

    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: dev

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

  AdminCidr:
    Description: IP address in CIDR format for admin access
    Type: String

  LatestAmazonLinuxAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet (AZ1)

  EC2EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: Prestashop EC2 instance

  EC2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EC2EIP.AllocationId
      InstanceId: !Ref EC2Instance

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Routes (AZ1)

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "server-sg"
      GroupDescription: "Security group with server ingress"
      VpcId: !Ref VPC

  ServerAdminIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: !Ref AdminCidr
      Description: SSH access
      FromPort: 22
      GroupId: !GetAtt ServerSecurityGroup.GroupId
      IpProtocol: tcp
      ToPort: 22

  ServerAccessIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: http access
      FromPort: 80
      GroupId: !GetAtt ServerSecurityGroup.GroupId
      IpProtocol: tcp
      ToPort: 80

#  ServerBucketReadRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#                - ec2.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Path: /
#      Policies:
#        - PolicyName: S3-read-only-access
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              - Effect: Allow
#                Action:
#                  - s3:GetObject
#                  - s3:ListBucket
#                Resource:
#                  - !Sub "arn:aws:s3:::${Artefacts}"
#                  - !Sub "arn:aws:s3:::${Artefacts}/*"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmazonLinuxAMI
      KeyName: !Ref KeyPair
#      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: t4g.nano
      SecurityGroupIds:
        - !Ref ServerSecurityGroup
      SubnetId: !Ref PublicSubnet1
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 8
            DeleteOnTermination: false
            Encrypted: true

#  InstanceProfile:
#    Type: 'AWS::IAM::InstanceProfile'
#    Properties:
#      Path: /
#      Roles:
#        - !Ref ServerBucketReadRole

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: MinecraftKeyPair
      PublicKeyMaterial: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcv6/40kT3czgeeCSzr5bZqRAmBr8xJxbG/qTZxYsiu31aO4Zn84wbsCIm+3UAra1dXXMbEq5Zgp9R9lf7RkblB+ty4HesSqlDioPTs4bNTWbPFFC9JHUQNZiO6Sg6NMGHgJnswQVExoCcqrtnr6LUUcV9O7Cjruj3azR++huB7UcU+QuSKAVDP3rBy7UCYizsb+kotHXe0woMtT9qyBXigMrzl+hMMeI6Po27JMVXCLPp2ilizpxrv6cQCbG2sl/A4ocrZkVLk2o8s1Y+AXDt+IA+5pzWpA7NJ8etQEtvZ4I/QWpEYv61mVvDIHGfvl2rC2QBwRJlsvmx8tm7hJ2qgo3NQKRyPppUeq8Ppoexj/IdCNakY7LwCANq+tRu21Z8TfkMiAX2Gm8/BHW7uLe39BYfn2OAUZIknFnKI0oT0De3Tq4gYlT/wP7v8Qlf2YlJwOFjKmH+EAGLtckUjon8eu8mWkdYEwjyY7pNsVKikbPxeMzdaR8YeV9JHoV40oE= ddunford@UK-RXY2Y22G2X

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1 ]]

  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1 ]]

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
